import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { site } from '../src/config.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'dist');
const reference = fs.readFileSync(path.join(root, 'src/brand.html'), 'utf8');
const favicon = reference.match(/<link rel="icon"[^>]+>/)[0];
const symbols = reference.match(/<svg class="symbols"[\s\S]*?<\/svg>/)[0];
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = name => '<svg class="icon" aria-hidden="true"><use href="#'+name+'"/></svg>';
const brand = '<svg aria-hidden="true"><use href="#logo"/></svg><span>Zähler<span class="brand-light">Werk</span></span>';
const contactLink = '/kontakt/?anliegen=demo';
const button = (label = 'Demo anfragen', href = contactLink, css = '') => '<a class="button '+css+'" href="'+href+'">'+label+'</a>';
const navLinks = [['/funktionen/','Funktionen'],['/fuer-verwaltungen/','Für Verwaltungen'],['/preise/','Preise'],['/sicherheit/','Sicherheit']];
const themeInit = '<script>try{var t=localStorage.getItem("zw-theme");if(t==="dark"||t==="light")document.documentElement.setAttribute("data-theme",t)}catch(e){}</'+'script>';
const themeToggle = '<button type="button" class="theme-toggle" id="theme-toggle" aria-pressed="false" aria-label="Dunkles Design aktivieren"><svg class="icon icon-sun" aria-hidden="true" viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v2.5M12 19.5V22M4.9 4.9l1.8 1.8M17.3 17.3l1.8 1.8M2 12h2.5M19.5 12H22M4.9 19.1l1.8-1.8M17.3 6.7l1.8-1.8"/></svg><svg class="icon icon-moon" aria-hidden="true" viewBox="0 0 24 24"><path d="M20.5 14.7A8.5 8.5 0 1 1 9.3 3.5a7 7 0 0 0 11.2 11.2Z"/></svg></button>';
const header = route => '<header class="site-header"><div class="nav-inner container"><a class="brand" href="/" aria-label="ZählerWerk Startseite">'+brand+'</a><nav id="navigation" aria-label="Hauptnavigation">'+navLinks.map(([href,label])=>'<a href="'+href+'"'+(href===route?' aria-current="page"':'')+'>'+label+'</a>').join('')+'<a href="/#faq">FAQ</a><a class="nav-cta" href="'+contactLink+'">Demo anfragen</a></nav><div class="nav-actions">'+button('Demo anfragen',contactLink,'compact')+themeToggle+'<button class="menu" type="button" aria-label="Menü öffnen" aria-expanded="false" aria-controls="navigation"><span></span><span></span></button></div></div></header>';
const footer = '<footer class="footer"><div class="container"><div class="footer-top"><a class="brand" href="/">'+brand+'</a><p>Einfach. Digital. Ablesen.</p></div><div class="footer-columns"><div><p>Digitale Zählerablesung für Hausverwaltungen.<br>Im Büro und direkt am Objekt.</p><a href="mailto:'+site.email+'">'+site.displayEmail+'</a><a href="tel:'+site.phone+'">'+site.displayPhone+'</a></div><nav aria-label="Produkt"><strong>Produkt</strong>'+navLinks.map(([href,label])=>'<a href="'+href+'">'+label+'</a>').join('')+'</nav><nav aria-label="Kontakt und Rechtliches"><strong>Kontakt & Informationen</strong><a href="/kontakt/">Kontakt & Demo</a><a href="/impressum/">Impressum</a><a href="/datenschutz/">Datenschutz</a></nav></div><div class="footer-bottom"><span>© 2026 ZählerWerk</span><span>Für professionelle Hausverwaltungen.</span><a class="back-top" href="#start">Nach oben ↑</a></div></div></footer>';
const lightbox = '<dialog id="screenshot-dialog" class="screenshot-dialog" aria-labelledby="screenshot-title"><div class="dialog-head"><h2 id="screenshot-title">ZählerWerk im Detail</h2><button type="button" class="dialog-close" aria-label="Produktansicht schließen">×</button></div><div class="dialog-body"><div class="dialog-image-wrap"><img alt="" id="dialog-image" width="1824" height="1368"></div></div><p class="dialog-caption" id="dialog-caption"></p></dialog>';
const screenshot = (type, caption, cls='', eager=false) => {
  const data = type==='desktop' ? ['zaehlerwerk-desktop.png',2732,2048,'Desktop-Übersicht mit Objekten, Zählern und offenen Ablesungen'] : type==='reading' ? ['zaehlerwerk-schnellablesung.jpeg',1206,2422,'Mobile Schnellablesung über die Zählernummer'] : ['zaehlerwerk-mobil.jpeg',1206,2436,'Mobile Heute-Übersicht mit offenen Ablesungen und Objekten'];
  return '<figure class="real-shot '+cls+'"><button type="button" class="shot-button" data-shot="'+type+'" aria-label="'+esc(caption)+' vergrößern"><span class="shot-crop '+(type==='desktop'?'desktop-crop':'mobile-crop')+'"><img src="/assets/'+data[0]+'" width="'+data[1]+'" height="'+data[2]+'" alt="'+data[3]+'" '+(eager?'fetchpriority="high"':'loading="lazy"')+' decoding="async"></span><span class="shot-enlarge" aria-hidden="true">↗</span></button><figcaption>'+caption+' <span>Vergrößern</span></figcaption></figure>';
};
const cta = (title='Ihre nächste Ablesung.<br><span>Einfach digital.</span>')=>'<section class="closing section"><div class="container reveal"><svg class="closing-mark" aria-hidden="true"><use href="#logo"/></svg><p class="eyebrow">ZÄHLERWERK KENNENLERNEN</p><h2>'+title+'</h2><p>Gemeinsam schauen wir auf Ihren Bestand.<br>Und auf einen einfacheren Ableseprozess.</p>'+button('Unverbindliche Demo anfragen')+'</div></section>';
const faqData = [
 ['Für wen ist ZählerWerk gemacht?','Für Hausverwaltungen und Immobilienverwaltungen, die Zählerablesungen für mehrere Objekte organisieren. ZählerWerk ergänzt Ihre vorhandene Verwaltungssoftware um einen spezialisierten Ableseprozess.'],
 ['Kann ich auch ohne Internet ablesen?','Auf mobilen Geräten können Ablesungen als Entwurf auf dem Gerät erfasst werden. Sobald wieder eine Verbindung besteht, werden die Entwürfe synchronisiert.'],
 ['Wie arbeitet mein Team damit?','Verwaltung und Mitarbeiter arbeiten mit eigenen Zugängen und passenden Rollen. Die Verwaltung behält den Überblick, während Mitarbeiter die operative Ablesearbeit erledigen.'],
 ['Lassen sich vorhandene Daten übernehmen?','Objekte, Einheiten und Zähler können aus vorhandenen ERP-Daten importiert oder direkt angelegt werden. Den Import Ihrer konkreten Dateien besprechen wir in der Demo.'],
 ['Was kostet ZählerWerk?','Die Preise richten sich nach der Anzahl Ihrer verwalteten Einheiten. Die monatliche Abrechnung beginnt bei 29 Euro. Den vollständigen Funktionsumfang erhalten Sie unabhängig von Ihrer Bestandsgröße. Die Staffelpreise und den Jahresrabatt finden Sie auf der Preisseite.'],
 ['Wie kann ich ZählerWerk testen?','Fragen Sie eine unverbindliche Demo an. Wir besprechen Ihren Ableseprozess, zeigen Ihnen die Anwendung und klären die nächsten Schritte.']
];
const faqs = data => data.map(([q,a])=>'<details><summary>'+q+'</summary><p>'+a+'</p></details>').join('');
const pageHero=(label,title,text)=>'<section class="page-hero container"><p class="eyebrow">'+label+'</p><h1>'+title+'</h1><p>'+text+'</p></section>';
const home = `
<section class="hero launch-hero"><div class="hero-copy container"><p class="eyebrow">DIGITALE ZÄHLERABLESUNG FÜR HAUSVERWALTUNGEN</p><h1>Weniger Aufwand.<br><span>Mehr Überblick.</span></h1><p class="hero-description"><span class="only-wide">Objekte, Zählerstände und Fotos. An einem Ort.<br>Im Büro organisiert. Vor Ort erledigt.</span><span class="only-narrow">Objekte, Zähler und Fotos an einem Ort.</span></p><div class="hero-links">${button('ZählerWerk kennenlernen')}<a class="text-link" href="#produkt">Die Anwendung ansehen ${icon('arrow')}</a></div><div class="hero-facts"><span>Mobil & Desktop</span><span>Offline-Entwürfe</span><span class="only-wide">Eigene Teamzugänge</span></div></div>
<div class="product-stage container" id="produkt">${screenshot('desktop','Die Desktop-Übersicht. Alles im Blick.','hero-desktop',true)}${screenshot('mobile','Die mobile Übersicht. Direkt am Objekt.','hero-mobile',true)}</div>
<p class="product-caption">Originalansichten aus ZählerWerk.</p></section>
<section class="intro section container" id="funktionen"><p class="eyebrow reveal">EINFACH ZUSAMMENGEDACHT</p><h2 class="statement reveal">Nicht mehr suchen.<br><span>Einfach wissen.</span></h2><div class="intro-bottom"><p class="intro-text reveal">Zählerstände auf Papier. Fotos auf dem Handy. Rückfragen im Büro. <strong>ZählerWerk bringt zusammen, was zusammengehört.</strong> Vom Objekt über die Einheit bis zur Ablesung.</p><div class="benefit-list reveal"><div>${icon('building')}Objekte und Einheiten</div><div>${icon('meter')}Zähler und Ablesungen</div><div>${icon('camera')}Fotos und Historie</div></div></div></section>
<section class="mobile-section" id="mobil"><div class="container mobile-grid"><div class="mobile-copy reveal"><p class="eyebrow">DIREKT ZUM RICHTIGEN ZÄHLER</p><h2>Nummer eingeben.<br><span>Ablesung starten.</span></h2><p>Die Schnellablesung findet Zähler, Objekt und Einheit über die Zählernummer. So gelangen Mitarbeiter ohne Umwege zur Erfassung.</p><a class="text-link" href="/funktionen/#mobile-ablesung">Mobile Funktionen entdecken ${icon('arrow')}</a><div class="offline-note">${icon('wifi')}<span>Kein Empfang? Als Entwurf erfassen.<br>Synchronisieren, sobald wieder eine Verbindung besteht.</span></div></div><div class="mobile-product reveal">${screenshot('reading','Schnellablesung auf dem Smartphone.','reading-shot')}</div></div></section>
<section class="section features-section"><div class="container"><div class="section-heading reveal"><p class="eyebrow">FÜR IHREN ARBEITSALLTAG</p><h2>Viele Objekte.<br><span>Ein klarer Ablauf.</span></h2></div><div class="launch-features">
<article class="launch-feature reveal">${icon('building')}<h3>Bestand übernehmen.</h3><p>Objekte, Einheiten und Zähler aus Ihrem ERP-System importieren und zentral organisieren.</p><a href="/funktionen/#import">Mehr zum Import <span>↗</span></a></article>
<article class="launch-feature reveal">${icon('camera')}<h3>Sauber dokumentieren.</h3><p>Stand, Foto und Historie gehören zum selben Zähler. Auch später bleibt die Ablesung nachvollziehbar.</p><a href="/funktionen/#dokumentation">Mehr zur Dokumentation <span>↗</span></a></article>
<article class="launch-feature reveal">${icon('users')}<h3>Im Team arbeiten.</h3><p>Eigene Zugänge und passende Rollen verbinden Verwaltung und Mitarbeiter vor Ort.</p><a href="/fuer-verwaltungen/">Mehr zur Zusammenarbeit <span>↗</span></a></article>
</div></div></section>
<section class="section process-section" id="ablauf"><div class="container"><div class="section-heading reveal"><p class="eyebrow">SO FUNKTIONIERT’S</p><h2>Vom Bestand.<br><span>Bis zur letzten Ablesung.</span></h2></div><ol class="steps"><li class="reveal"><span class="step-number">01</span><h3>Bestand übernehmen.</h3><p>Objekte, Einheiten und Zähler importieren oder direkt anlegen.</p></li><li class="reveal"><span class="step-number">02</span><h3>Ablesung planen.</h3><p>Jahresablesungen vorbereiten und die Arbeit im Team organisieren.</p></li><li class="reveal"><span class="step-number">03</span><h3>Vor Ort erfassen.</h3><p>Zählerstand und Foto zuordnen. Bei Bedarf offline als Entwurf.</p></li><li class="reveal"><span class="step-number">04</span><h3>Überblick behalten.</h3><p>Offene Ablesungen erkennen und frühere Stände nachvollziehen.</p></li></ol></div></section>
<section class="price-teaser"><div class="container price-teaser-inner"><div><p class="eyebrow">EIN PREIS. ALLE FUNKTIONEN.</p><h2>Passt zu Ihrem Bestand.</h2><p>Abrechnung pro verwalteter Einheit.<br>Mit Mengenstaffel und 10 % Rabatt bei jährlicher Abrechnung.</p></div><div class="teaser-number"><span>Monatliche Abrechnung ab</span><strong>29 €<small>/Monat</small></strong><a class="text-link" href="/preise/">Preis berechnen ${icon('arrow')}</a></div></div></section>
<section class="section faq-section" id="faq"><div class="container faq-layout"><div class="reveal"><p class="eyebrow">GUT ZU WISSEN</p><h2>Noch Fragen?<br><span>Gerne.</span></h2><a class="text-link" href="/kontakt/">Kontakt aufnehmen ${icon('arrow')}</a></div><div class="faq-list reveal">${faqs(faqData)}</div></div></section>${cta()}`;

const features = pageHero('FUNKTIONEN','Eine Anwendung.<br><span>Der ganze Ableseprozess.</span>','ZählerWerk verbindet Ihren Bestand mit der Arbeit vor Ort. Klar strukturiert, nachvollziehbar und für Ihr Team zugänglich.')+`
<section class="container feature-detail" id="import"><div><p class="eyebrow">01 · BESTAND & IMPORT</p><h2>Vorhandene Daten.<br><span>Einfach übernehmen.</span></h2><p>Importieren Sie Objekte, Einheiten und Zähler aus bestehenden ERP-Daten. Neue Objekte lassen sich auch direkt in ZählerWerk anlegen.</p><ul class="check-list"><li>Klare Zuordnung von Einheiten zu Objekten</li><li>Hauptzähler und Einheitenzähler zentral verwalten</li><li>Zähler über ihre Nummer eindeutig auffinden</li></ul></div><div class="detail-panel"><span class="detail-index">01</span><h3>Objekt.<br>Einheit.<br>Zähler.</h3><p>Eine Struktur, auf der jede Ablesung aufbaut.</p></div></section>
<section class="feature-band" id="mobile-ablesung"><div class="container feature-detail"><div class="detail-mobile">${screenshot('reading','Zählernummer eingeben und Ablesung starten.')}</div><div><p class="eyebrow">02 · MOBILE ABLESUNG</p><h2>Am Zähler.<br><span>Am richtigen Ort.</span></h2><p>Über Objekt, Einheit oder Zählernummer finden Mitarbeiter den passenden Zähler. Der letzte Stand steht zum Vergleich bereit.</p><ul class="check-list"><li>Zählerstände im Büro und unterwegs erfassen</li><li>Fotos direkt der Ablesung zuordnen</li><li>Ohne Empfang als Entwurf weiterarbeiten</li><li>Entwürfe bei bestehender Verbindung synchronisieren</li></ul></div></div></section>
<section class="container feature-detail" id="dokumentation"><div><p class="eyebrow">03 · DOKUMENTATION & HISTORIE</p><h2>Ein Stand.<br><span>Mit Zusammenhang.</span></h2><p>Jedes Foto gehört zur entsprechenden Ablesung. Frühere Zählerstände bleiben chronologisch einsehbar – als Grundlage für Rückfragen und Prüfungen.</p><ul class="check-list"><li>Fotos mit Bezug zu Zähler und Ablesung</li><li>Historie je Zähler</li><li>Frühere Stände zum Nachschlagen</li></ul></div><div class="detail-panel light"><span class="detail-index">03</span><h3>Stand.<br>Foto.<br>Historie.</h3><p>Zusammen dokumentiert. Später nachvollziehbar.</p></div></section>
<section class="feature-band"><div class="container section"><div class="section-heading"><p class="eyebrow">04 · PLANUNG & ZUSAMMENARBEIT</p><h2>Jahresablesung.<br><span>Mit Überblick.</span></h2><p class="section-description">Sehen Sie, wo Zählerstände fehlen, welche Objekte bearbeitet werden und was Ihr Team als Nächstes angeht.</p></div>${screenshot('desktop','Objekte und offene Ablesungen in der Desktop-Ansicht.')}<div class="launch-features compact-features"><article><h3>Fortschritt erkennen.</h3><p>Offene Zähler und der Erfassungsstand je Objekt bleiben sichtbar.</p></article><article><h3>Zugänge trennen.</h3><p>Jede Person arbeitet mit einem eigenen Benutzerkonto.</p></article><article><h3>Rollen passend vergeben.</h3><p>Administrative Aufgaben und operative Ablesearbeit sind getrennt.</p></article></div></div></section>${cta()}`;

const management = pageHero('FÜR HAUSVERWALTUNGEN','Ihr Büro. Ihr Team.<br><span>Eine gemeinsame Übersicht.</span>','Für kleine Verwaltungen mit wachsendem Bestand und Teams, die viele Objekte parallel ablesen.')+`
<section class="container management-grid"><article class="feature-card"><p class="feature-category">IM BÜRO</p><h2>Planen.<br>Ordnen.<br><span>Überblicken.</span></h2><p>Objekte und Zähler pflegen, die Jahresablesung koordinieren und offene Ablesungen erkennen. Benutzer und Rollen steuern den Zugriff.</p></article><article class="feature-card team-card"><p class="feature-category">VOR ORT</p><h2>Finden.<br>Erfassen.<br><span>Dokumentieren.</span></h2><p>Zähler suchen, Stände eintragen und Fotos hinzufügen. Mobil arbeiten und bei fehlender Verbindung Entwürfe auf dem Gerät erfassen.</p></article></section>
<section class="container section"><div class="section-heading"><p class="eyebrow">WAS SICH IM ALLTAG ÄNDERT</p><h2>Weniger Übergaben.<br><span>Mehr Zusammenhang.</span></h2></div><div class="comparison"><div class="comparison-head"><span>Bisher</span><span>Mit ZählerWerk</span></div>${[['Handschriftliche Papierlisten','Zählerstände direkt digital erfassen'],['Fotos in der Kamerarolle','Fotos fest der Ablesung zugeordnet'],['Getrennte Tabellen je Objekt','Bestand in einer gemeinsamen Übersicht'],['Stammdaten neu anlegen','Bestehende ERP-Daten importieren'],['Rückfragen ohne Kontext','Historie und Zuordnung am Zähler']].map(([a,b])=>'<div class="comparison-row"><span>'+a+'</span><strong>'+icon('check')+b+'</strong></div>').join('')}</div></section>
<section class="mobile-section"><div class="container mobile-grid"><div class="mobile-copy"><p class="eyebrow">DER NÄCHSTE EINSATZ IM BLICK</p><h2>Heute wissen,<br><span>was noch offen ist.</span></h2><p>Die mobile Startseite zeigt offene Ablesungen und Objekte. Ihr Team steigt direkt in die Arbeit ein.</p></div><div class="mobile-product">${screenshot('mobile','Heute-Übersicht mit offenen Ablesungen.')}</div></div></section>${cta()}`;

const pricePage = pageHero('PREISE','Ihr Bestand.<br><span>Ihr Preis.</span>','Ein vollständiger Funktionsumfang. Ein Preis pro verwalteter Einheit. Berechnen Sie die Kosten für Ihren Bestand.')+`
<section class="container pricing-layout"><form class="price-calculator" id="price-calculator"><div class="calculator-top"><label for="units">Verwaltete Einheiten</label><fieldset class="billing-choice"><legend class="sr-only">Abrechnungszeitraum</legend><label><input type="radio" name="billing" value="monthly" checked><span>Monatlich</span></label><label><input type="radio" name="billing" value="annual"><span>Jährlich <b>−10 %</b></span></label></fieldset></div><div class="units-input"><input type="number" id="units" name="units" min="1" max="1000000" step="1" value="300" inputmode="numeric" required aria-describedby="price-error"><span>Einheiten</span></div><label class="sr-only" for="unit-range">Bestandsgröße auswählen</label><input type="range" id="unit-range" min="1" max="6000" step="1" value="300"><div class="unit-presets">${[100,300,750,1500,5500].map(n=>'<button type="button" data-units="'+n+'">'+n.toLocaleString('de-DE')+'</button>').join('')}</div><p id="price-error" role="alert" hidden>Bitte geben Sie eine ganze Zahl zwischen 1 und 1.000.000 ein.</p><div class="price-result" aria-live="polite" aria-atomic="true"><span id="price-period">Bei monatlicher Abrechnung</span><div><output id="price-total">57 €</output><span id="price-suffix">/Monat</span></div><p id="price-description">0,19 € pro Einheit · Mindestpreis 29 €/Monat</p><p id="price-annual" hidden></p><a class="button" id="price-cta" href="/kontakt/?anliegen=demo&units=300&billing=monthly">Demo für Ihren Bestand anfragen</a></div><p class="price-note">Unverbindliche Preisorientierung. Die steuerliche Behandlung und den verbindlichen Gesamtpreis erhalten Sie mit Ihrem persönlichen Angebot.</p><noscript><p>Ohne JavaScript zeigt der Rechner das Beispiel für 300 Einheiten. Die Staffelpreise stehen in der Tabelle unten.</p></noscript></form>
<aside class="pricing-included"><p class="eyebrow">IMMER DABEI</p><h2>Alle Funktionen.<br><span>Auch für kleine Bestände.</span></h2><ul class="check-list"><li>Objekte, Einheiten und Zähler</li><li>Import bestehender ERP-Daten</li><li>Mobile Ablesung mit Offline-Entwürfen</li><li>Fotos, Historie und Jahresablesung</li><li>Beliebig viele Benutzer und Rollen</li><li>Zukünftige Funktionsupdates</li><li>E-Mail-Support</li></ul></aside></section>
<section class="container section pricing-details"><div><p class="eyebrow">DIE MENGENSTAFFEL</p><h2>Einfach<br><span>nachvollziehbar.</span></h2><p>Der Satz Ihrer Bestandsgröße gilt für alle verwalteten Einheiten. Zähler und Benutzer werden nicht zusätzlich berechnet.</p></div><div class="table-scroll"><table class="price-table"><caption>Preise bei monatlicher Abrechnung</caption><thead><tr><th scope="col">Bestand</th><th scope="col">Pro Einheit / Monat</th></tr></thead><tbody><tr><th scope="row">1–500 Einheiten</th><td>0,19 €</td></tr><tr><th scope="row">501–2.000 Einheiten</th><td>0,15 €</td></tr><tr><th scope="row">2.001–5.000 Einheiten</th><td>0,12 €</td></tr><tr><th scope="row">Über 5.000 Einheiten</th><td>Individuelles Angebot</td></tr></tbody></table><p class="price-note">Mindestens 29 € pro Monat bei monatlicher Abrechnung. Jährliche Abrechnung: 10 % Rabatt auf den Jahresbetrag. Einmalige Jahreszahlung, im Rechner zusätzlich als Monatsdurchschnitt dargestellt.</p></div></section>
<section class="section faq-section"><div class="container faq-layout"><h2>Gut zu wissen.<br><span>Vor dem Start.</span></h2><div class="faq-list">${faqs([['Was zählt als Einheit?','Eine im Bestand angelegte, abrechenbare Einheit – beispielsweise eine Wohnung, ein Gewerbe oder ein Stellplatz. Die Anzahl der Zähler je Einheit verändert den Preis nicht.'],['Wie funktioniert die Jahresabrechnung?','Der monatliche Grundbetrag wird mit zwölf multipliziert und um 10 % reduziert. Im Rechner sehen Sie den Jahresbetrag und den entsprechenden Monatsdurchschnitt.'],['Wie lange läuft der Vertrag?','Vertragslaufzeit, Wechsel des Abrechnungszeitraums und Einführung besprechen wir im persönlichen Angebot.'],['Was passiert oberhalb von 5.000 Einheiten?','Für mehr als 5.000 Einheiten erstellen wir ein individuelles Angebot und besprechen die Einführung und Betreuung Ihres Bestands.']])}</div></div></section>${cta()}`;

const security = pageHero('SICHERHEIT & ZUSAMMENARBEIT','Klare Zugänge.<br><span>Klare Verantwortung.</span>','ZählerWerk verbindet Benutzer, Rollen und nachvollziehbare Datenstrukturen für den professionellen Ablesealltag.')+`
<section class="container security-grid"><article class="feature-card">${icon('users')}<h2>Eigener Zugang.<br><span>Für jede Person.</span></h2><p>Jeder Mitarbeiter arbeitet mit einem eigenen Konto. Administrative Aufgaben und operative Ablesearbeit werden über Rollen getrennt.</p></article><article class="feature-card">${icon('building')}<h2>Daten mit<br><span>Zusammenhang.</span></h2><p>Objekte, Einheiten, Zähler, Ablesungen und Fotos sind miteinander verknüpft. Die Historie ermöglicht es, frühere Stände nachzuvollziehen.</p></article></section>
<section class="container section security-note"><p class="eyebrow">TRANSPARENT VOR DEM START</p><h2>Die richtigen Fragen.<br><span>Gemeinsam klären.</span></h2><p>Sie benötigen Informationen zur Datenverarbeitung, zum Betrieb oder zur Auftragsverarbeitung? Sprechen Sie uns an. So lassen sich die Anforderungen Ihrer Verwaltung vor dem Einsatz besprechen.</p><p>Zertifizierungen, Prüfsiegel oder Garantien zu Datenstandorten werden hier nicht behauptet, solange entsprechende Nachweise nicht vorliegen.</p><a class="text-link" href="/kontakt/?anliegen=datenschutz">Fragen zur Datenverarbeitung stellen ${icon('arrow')}</a></section>${cta()}`;

const contact = pageHero('KONTAKT & DEMO','Lernen wir<br><span>Ihren Bestand kennen.</span>','Erzählen Sie uns von Ihrer Verwaltung. Gemeinsam schauen wir, wie ZählerWerk Ihren Ableseprozess vereinfachen kann.')+`
<section class="container contact-layout"><aside class="contact-aside"><p class="eyebrow">IHR DIREKTER KONTAKT</p><h2>Luis Ruppel</h2><p>ZählerWerk<br>Gehrde, Deutschland</p><a class="contact-email" href="mailto:${site.email}">${site.displayEmail}</a><a class="contact-phone" href="tel:${site.phone}">${site.displayPhone}</a><div class="contact-agenda"><h3>Darüber sprechen wir.</h3><ol><li>Ihr Bestand und Ihr bisheriger Ablauf</li><li>ZählerWerk im Büro und vor Ort</li><li>Datenimport, Preis und nächste Schritte</li></ol></div><a class="text-link" href="/preise/">Vorab Preis berechnen ${icon('arrow')}</a></aside>
<div class="contact-form-card"><h2>Ihre Anfrage.</h2><p class="form-intro">Wir antworten Ihnen zeitnah per E-Mail.</p><form id="contact-form"><label for="inquiry">Ihr Anliegen</label><select id="inquiry" name="inquiry"><option value="demo">Demo anfragen</option><option value="kontakt">Allgemeine Anfrage</option><option value="angebot">Individuelles Angebot</option><option value="datenschutz">Datenverarbeitung & Auftragsverarbeitung</option></select><div class="field-grid"><div><label for="name">Vorname und Nachname *</label><input id="name" name="name" autocomplete="name" maxlength="120" required></div><div><label for="company">Hausverwaltung / Unternehmen *</label><input id="company" name="company" autocomplete="organization" maxlength="180" required></div><div><label for="email">E-Mail-Adresse *</label><input id="email" name="email" type="email" autocomplete="email" maxlength="180" required></div><div><label for="phone">Telefon <span>(optional)</span></label><input id="phone" name="phone" type="tel" autocomplete="tel" maxlength="60"></div><div><label for="contact-units">Verwaltete Einheiten <span>(optional)</span></label><input id="contact-units" name="units" type="number" min="1" max="1000000" step="1" inputmode="numeric"></div><div><label for="contact-billing">Abrechnung</label><select id="contact-billing" name="billing"><option value="">Noch offen</option><option value="monthly">Monatlich</option><option value="annual">Jährlich</option></select></div></div><label for="message">Ihre Nachricht *</label><textarea id="message" name="message" rows="5" minlength="10" maxlength="2500" required placeholder="Was möchten Sie über ZählerWerk erfahren?"></textarea><p class="form-privacy">Ihre Angaben werden nur zur Bearbeitung Ihrer Anfrage verwendet. Mehr dazu in den <a href="/datenschutz/">Datenschutzhinweisen</a>. Pflichtfelder sind mit * markiert.</p><button type="submit" class="button" disabled>Anfrage senden ${icon('arrow')}</button><p id="send-error" hidden role="alert">Die Anfrage konnte nicht gesendet werden. Bitte versuchen Sie es erneut oder schreiben Sie uns direkt an <a href="mailto:${site.email}">${site.displayEmail}</a>.</p><noscript><p>Bitte senden Sie Ihre Anfrage direkt an <a href="mailto:${site.email}">${site.displayEmail}</a> oder rufen Sie uns an.</p></noscript></form><div id="email-ready" hidden role="status"><h3>Vielen Dank.</h3><p>Ihre Nachricht ist bei uns angekommen. Wir melden uns zeitnah bei Ihnen.</p></div></div></section>`;

const legal = pageHero('RECHTLICHES','Impressum.','Angaben zum Anbieter dieser Website.')+`
<article class="container legal-content"><section><h2>Anbieter</h2><p>ZählerWerk<br>${site.owner}<br>${site.street}<br>${site.city}<br>Deutschland</p></section><section><h2>Kontakt</h2><p>Telefon: <a href="tel:${site.phone}">${site.displayPhone}</a><br>E-Mail: <a href="mailto:${site.email}">${site.displayEmail}</a></p></section><section><h2>Verantwortlich für den Inhalt</h2><p>Luis Ruppel<br>Anschrift wie oben.</p></section><section><h2>Verbraucherstreitbeilegung</h2><p>Wir sind nicht verpflichtet und nicht bereit, an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p></section><p class="legal-date">Stand: September 2026</p></article>`;

const privacy = pageHero('RECHTLICHES','Datenschutz.','Informationen zur Verarbeitung personenbezogener Daten auf dieser Website.')+`
<article class="container legal-content">
<section><h2>1. Verantwortlicher</h2><p>${site.owner}<br>${site.street}<br>${site.city}<br>Deutschland<br>E-Mail: <a href="mailto:${site.email}">${site.displayEmail}</a><br>Telefon: <a href="tel:${site.phone}">${site.displayPhone}</a></p></section>
<section><h2>2. Umfang dieser Hinweise</h2><p>Diese Informationen betreffen die Informationswebsite von ZählerWerk. Die Verarbeitung innerhalb der ZählerWerk-Anwendung sowie die Verarbeitung im Auftrag einer Hausverwaltung sind hiervon zu unterscheiden und Gegenstand der jeweiligen Vereinbarungen für die Anwendung.</p></section>
<section><h2>3. Bereitstellung der Website</h2><p>Diese Website wird über die Plattform Netlify bereitgestellt (Netlify, Inc., USA). Beim Abruf werden insbesondere IP-Adresse, Zeitpunkt, angeforderte Ressource sowie Browser- und Geräteinformationen technisch verarbeitet.</p><p>Die Verarbeitung dient der Auslieferung, Stabilität und Absicherung der Website. Grundlage ist unser berechtigtes Interesse an einer funktionsfähigen und sicheren Website gemäß Art. 6 Abs. 1 lit. f DSGVO.</p><p>Weitere Informationen des Plattformanbieters: <a href="https://www.netlify.com/privacy/" rel="noopener noreferrer" target="_blank">Datenschutzhinweise von Netlify</a>. Bei Nutzung dieses Dienstes kann eine Verarbeitung außerhalb des Europäischen Wirtschaftsraums stattfinden. Die dort beschriebenen Empfänger, Speicherkriterien und Übermittlungsmechanismen sind zu beachten.</p></section>
<section><h2>4. Kontakt per E-Mail und Telefon</h2><p>Wenn Sie uns kontaktieren, verarbeiten wir Ihre Kontaktdaten und den Inhalt Ihrer Anfrage, um Ihnen zu antworten, eine Demo zu vereinbaren oder ein Angebot vorzubereiten. Je nach Anliegen erfolgt die Verarbeitung zur Durchführung vorvertraglicher Maßnahmen nach Art. 6 Abs. 1 lit. b DSGVO oder aufgrund unseres berechtigten Interesses an der Beantwortung geschäftlicher Anfragen nach Art. 6 Abs. 1 lit. f DSGVO.</p><p>Wenn Sie das Kontaktformular absenden, werden Ihre Eingaben an unseren Server übertragen und von dort als E-Mail an unsere Kontaktadresse versendet. Für den Versand setzen wir den Dienst Resend ein (Resend, Inc., USA). Die Zustellung an unser Postfach erfolgt anschließend über den Weiterleitungsdienst ImprovMX (ImprovMX SAS, Frankreich). Eine dauerhafte Speicherung der Formulareingaben in einer Datenbank findet nicht statt; die Nachricht verbleibt in unserem E-Mail-Postfach.</p><p>Weitere Informationen der eingesetzten Dienste: <a href="https://resend.com/legal/privacy-policy" rel="noopener noreferrer" target="_blank">Datenschutzhinweise von Resend</a> und <a href="https://improvmx.com/privacy/" rel="noopener noreferrer" target="_blank">Datenschutzhinweise von ImprovMX</a>. Bei Resend kann eine Verarbeitung außerhalb des Europäischen Wirtschaftsraums stattfinden.</p><p>Ihre Kontaktangaben werden zur Bearbeitung der Anfrage verwendet. Sie müssen keine optionalen Angaben machen. Ohne erreichbare Kontaktadresse können wir Ihre Anfrage nicht beantworten.</p></section>
<section><h2>5. Speicherdauer</h2><p>Kontaktanfragen werden nur so lange aufbewahrt, wie sie zur Bearbeitung und gegebenenfalls zur anschließenden Geschäftsbeziehung erforderlich sind. Bestehende gesetzliche Aufbewahrungspflichten bleiben unberührt. Für technisch durch Plattformanbieter verarbeitete Daten gelten die Speicherkriterien der jeweiligen Dienste.</p></section>
<section><h2>6. Cookies, Schriftarten und Reichweitenmessung</h2><p>Diese Website setzt keine Cookies zu Werbe- oder Trackingzwecken und bindet keine extern geladenen Schriftarten oder eingebetteten Videos ein. Der Preisrechner arbeitet lokal im Browser. Lediglich Ihre Auswahl zwischen hellem und dunklem Design wird auf Wunsch lokal in Ihrem Browser gespeichert, damit sie beim nächsten Besuch erhalten bleibt.</p><p>Wir setzen derzeit keinen Analyse- oder Trackingdienst ein. Die Auslieferung der Website erzeugt lediglich die oben unter Punkt 3 beschriebenen technischen Server-Protokolle.</p></section>
<section><h2>7. Ihre Rechte</h2><p>Unter den gesetzlichen Voraussetzungen haben Sie Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung sowie Datenübertragbarkeit. Soweit eine Verarbeitung auf Ihrer Einwilligung beruht, können Sie diese für die Zukunft widerrufen.</p><p><strong>Widerspruchsrecht:</strong> Gegen eine Verarbeitung auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO können Sie aus Gründen Ihrer besonderen Situation Widerspruch einlegen.</p><p>Für Ihre Anliegen erreichen Sie uns unter <a href="mailto:${site.email}">${site.displayEmail}</a>. Sie können sich außerdem bei einer Datenschutzaufsichtsbehörde beschweren, beispielsweise beim <a href="https://www.lfd.niedersachsen.de/" rel="noopener noreferrer" target="_blank">Landesbeauftragten für den Datenschutz Niedersachsen</a>.</p></section>
<section><h2>8. Automatisierte Entscheidungen</h2><p>Über diese Informationswebsite werden keine automatisierten Entscheidungen mit rechtlicher oder vergleichbarer erheblicher Wirkung und kein Profiling durchgeführt.</p></section><p class="legal-date">Stand: September 2026</p></article>`;

const pages = [
 ['/', 'Digitale Zählerablesung für Hausverwaltungen', 'ZählerWerk bündelt Objekte, Zählerstände und Fotos. Digitale Ablesung im Büro und mobil, mit Offline-Entwürfen und klaren Teamrollen.', home],
 ['/funktionen/', 'Funktionen', 'ERP-Datenimport, Zählerverwaltung, mobile Ablesung, Fotos, Historie und Jahresablesung – die Funktionen von ZählerWerk im Überblick.', features],
 ['/fuer-verwaltungen/', 'Für Hausverwaltungen', 'Ein gemeinsamer Ableseprozess für Verwaltung und Außendienst. Entdecken Sie ZählerWerk für Ihren Immobilienbestand.', management],
 ['/preise/', 'Preise & Preisrechner', 'Berechnen Sie die Kosten für Ihren Bestand. Staffelpreise je Einheit, mindestens 29 Euro bei monatlicher Abrechnung und 10 Prozent Jahresrabatt.', pricePage],
 ['/sicherheit/', 'Sicherheit & Zusammenarbeit', 'Eigene Benutzerkonten, rollenbasierte Zugriffe und nachvollziehbare Zählerdaten. Informationen für den professionellen Einsatz.', security],
 ['/kontakt/', 'Kontakt & Demo', 'Kontaktieren Sie Luis Ruppel für eine persönliche ZählerWerk-Demo. E-Mail: kontakt@zählerwerk.eu. Telefon: 0160 6141200.', contact],
 ['/impressum/', 'Impressum', 'Anbieter- und Kontaktangaben für ZählerWerk: Luis Ruppel, Gehrde.', legal],
 ['/datenschutz/', 'Datenschutz', 'Informationen zum Datenschutz auf der ZählerWerk-Website und bei Kontaktanfragen.', privacy]
];
for (const [route, title, description, content] of pages) {
 const target = path.join(out, route, 'index.html');
 fs.mkdirSync(path.dirname(target), { recursive: true });
 const structured = route==='/' ? [{ '@context':'https://schema.org', '@type':'SoftwareApplication', name:site.name, applicationCategory:'BusinessApplication', operatingSystem:'Web', description, url:site.origin+'/' },{'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqData.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))}] : [];
 const html = '<!doctype html>\n<html lang="de"><head><meta charset="utf-8">'+themeInit+'<meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#10644d" id="theme-color-meta"><title>'+esc(title)+' | ZählerWerk</title><meta name="description" content="'+esc(description)+'"><meta name="robots" content="'+(site.indexable?'index,follow':'noindex,nofollow')+'"><link rel="canonical" href="'+site.origin+route+'"><meta property="og:type" content="website"><meta property="og:locale" content="de_DE"><meta property="og:site_name" content="ZählerWerk"><meta property="og:title" content="'+esc(title)+' | ZählerWerk"><meta property="og:description" content="'+esc(description)+'"><meta property="og:url" content="'+site.origin+route+'"><meta property="og:image" content="'+site.origin+'/og.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="ZählerWerk – Weniger Aufwand. Mehr Überblick."><meta name="twitter:card" content="summary_large_image"><link rel="apple-touch-icon" href="/apple-touch-icon.png">'+favicon+'<link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/launch.css"><script type="module" src="/main.js"></script>'+structured.map(s=>'<script type="application/ld+json">'+JSON.stringify(s).replace(/</g,'\\u003c')+'</script>').join('')+'</head><body id="start"><a class="skip" href="#inhalt">Zum Inhalt</a>'+symbols+header(route)+'<main id="inhalt">'+content+'</main>'+footer+lightbox+'</body></html>';
 fs.writeFileSync(target,html);
}
const notFound = '<!doctype html><html lang="de"><head><meta charset="utf-8">'+themeInit+'<meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Seite nicht gefunden | ZählerWerk</title><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/launch.css">'+favicon+'</head><body id="start">'+symbols+header('/404/')+'<main id="inhalt" class="page-hero container"><p class="eyebrow">404</p><h1>Hier geht es<br><span>nicht weiter.</span></h1><p>Die gesuchte Seite ist nicht verfügbar.</p>'+button('Zur Startseite','/')+'</main>'+footer+'<script type="module" src="/main.js"></script></body></html>';
fs.writeFileSync(path.join(out,'404.html'),notFound);
fs.copyFileSync(path.join(root,'src/pricing.mjs'),path.join(out,'pricing.mjs'));
fs.writeFileSync(path.join(out,'robots.txt'),site.indexable?'User-agent: *\nAllow: /\nSitemap: '+site.origin+'/sitemap.xml\n':'User-agent: *\nDisallow: /\n');
fs.writeFileSync(path.join(out,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+pages.map(([route])=>'<url><loc>'+site.origin+route+'</loc></url>').join('')+'</urlset>');
console.log('Built '+pages.length+' pages, 404, robots and sitemap. Indexing: '+site.indexable);